# Tensors 

Most modern deep learning tasks involve working with multi-dimensional arrays of numbers, known as tensors. A Tensor is a number , vector, matrix or n-dimensional array that is used to store and manipulate data.

In [1]:
import torch
import numpy as np

In [2]:
def tensor_info(tensor):
    'This function takes a tensor and prints the data-type and shape of a tensor'
    return f"The shape of the tensor is {tensor.shape} and data-type is {tensor.dtype}"

In [3]:
t2 = torch.tensor([1,2,3,4.])
tensor_info(t2)

'The shape of the tensor is torch.Size([4]) and data-type is torch.float32'

The `torch.tensor` is used to create Tensors and for `t2` when we are not explicitly specifying the data-type pytorch will choose the best fit internally since we have 3 integers and one floating point number it sets the dtype to `torch.float32`

In [4]:
t3 = torch.tensor([[2,4,4],
                  [7,4,6],
                  [9,3,0],
                  [7,2,7]], dtype = torch.int16)
tensor_info(t3)

'The shape of the tensor is torch.Size([4, 3]) and data-type is torch.int16'

For `t3`, we explicitly set the dtype to `torch.int16`

In [5]:
t3.view(2,6)

tensor([[2, 4, 4, 7, 4, 6],
        [9, 3, 0, 7, 2, 7]], dtype=torch.int16)

When training neural networks you will spend a lot of time manipulating tensors to certain shapes to perform calculations and view is widely for this purpose. `torch.Tensor.view` helps in manipulating shapes as long as both of the shapes multiply to the same 

In [6]:
t3.view(6,-1), t3.view(-1,4)

(tensor([[2, 4],
         [4, 7],
         [4, 6],
         [9, 3],
         [0, 7],
         [2, 7]], dtype=torch.int16),
 tensor([[2, 4, 4, 7],
         [4, 6, 9, 3],
         [0, 7, 2, 7]], dtype=torch.int16))

When we give one of the dimension and specify other as `-1` then pytorch will automatically calculates and set the other dimension

In [7]:
x = torch.rand(2,3,4, requires_grad=True)
w = torch.rand(2,3,4, requires_grad=True)
b = torch.rand(1,1,1, requires_grad=True)

y = w * x + b
y

tensor([[[0.4079, 0.4342, 0.3647, 0.5249],
         [0.2942, 0.4109, 0.2930, 0.3044],
         [0.9253, 0.5588, 0.3376, 0.3189]],

        [[0.3207, 0.2630, 0.2699, 0.4508],
         [0.3536, 0.7747, 0.6288, 0.2800],
         [0.2869, 1.0981, 0.4720, 0.3385]]], grad_fn=<AddBackward0>)

we set `requires_grad=True` to compute gradients during back-propagation when training a neural network

In [9]:
y_sum = y.sum()
y_sum

tensor(10.7120, grad_fn=<SumBackward0>)

In [11]:
y_sum.backward()

In [12]:
# Print the gradients
print("Gradients of x:", x.grad)
print("Gradients of w:", w.grad)
print("Gradients of b:", b.grad)

Gradients of x: tensor([[[0.9353, 0.1815, 0.6642, 0.3850],
         [0.2306, 0.6491, 0.1492, 0.0644],
         [0.8541, 0.9033, 0.5557, 0.2417]],

        [[0.9412, 0.9460, 0.0585, 0.2253],
         [0.3330, 0.9276, 0.5008, 0.0526],
         [0.0780, 0.9148, 0.2306, 0.4297]]])
Gradients of w: tensor([[[0.1651, 0.9954, 0.1674, 0.7047],
         [0.1762, 0.2424, 0.2642, 0.7897],
         [0.7865, 0.3379, 0.1513, 0.2705]],

        [[0.0714, 0.0100, 0.2796, 0.8752],
         [0.3004, 0.5619, 0.7493, 0.5016],
         [0.4283, 0.9232, 0.9472, 0.1977]]])
Gradients of b: tensor([[[24.]]])
